-- MySQL Script generated by MySQL Workbench
-- Fri Jul 27 17:40:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema webdevprj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webdevprj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webdevprj` DEFAULT CHARACTER SET utf8 ;
USE `webdevprj` ;

-- -----------------------------------------------------
-- Table `webdevprj`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webdevprj`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL DEFAULT 'USERNAME',
  `password` LONGTEXT NOT NULL,
  `score` INT(11) NOT NULL DEFAULT '0',
  `level` INT(11) NOT NULL DEFAULT '1',
  `win` INT(11) NOT NULL DEFAULT '0',
  `lose` INT(11) NOT NULL DEFAULT '0',
  `idroom` INT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabella utenti';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
